const fs = require('fs');
const path = require('path');
const commands = new Map();
function loadCommands() {
  commands.clear();
  const commandFiles = fs
    .readdirSync(__dirname)
    .filter(
      (file) =>
        file.endsWith('.js') &&
        file !== 'index.js'
    )
    .sort();
  for (const file of commandFiles) {
    try {
      const filePath = path.join(
        __dirname,
        file
      );
      delete require.cache[
        require.resolve(filePath)
      ];
      const command =
        require(filePath);
      if (
        !command ||
        typeof command !== 'object' ||
        !command.name ||
        typeof command.execute !== 'function'
      ) {
        console.warn(
          `[Commands] Skipping invalid command: ${file}`
        );
        continue;
      }
      const name =
        String(command.name)
          .trim()
          .toLowerCase();
      if (!name) {
        continue;
      }
      commands.set(
        name,
        command
      );
      if (
        Array.isArray(command.aliases)
      ) {
        for (
          const alias of command.aliases
        ) {
          const aliasName =
            String(alias)
              .trim()
              .toLowerCase();
          if (
            aliasName &&
            !commands.has(aliasName)
          ) {
            commands.set(
              aliasName,
              command
            );
          }
        }
      }
      console.log(
        `✅ Command loaded: ${name}`
      );
    } catch (error) {
      console.error(
        `[Commands] Failed to load ${file}:`,
        error.message
      );
    }
  }
  console.log(
    `✅ Command system loaded ${commands.size} command/alias entries`
  );
}
function getCommandList() {
  const uniqueCommands =
    new Map();
  for (
    const command of commands.values()
  ) {
    const name =
      String(command.name)
        .trim()
        .toLowerCase();
    if (
      !uniqueCommands.has(name)
    ) {
      uniqueCommands.set(
        name,
        command
      );
    }
  }
  return Array.from(
    uniqueCommands.values()
  ).map(
    (command) => ({
      name:
        command.name,
      aliases:
        Array.isArray(
          command.aliases
        )
          ? command.aliases
          : [],
      category:
        command.category ||
        'General',
      description:
        command.description ||
        ''
    })
  );
}
function normalizeInput(input) {
  let text =
    String(input || '')
      .trim();
  const prefixed =
    text.startsWith('.');
  if (prefixed) {
    text =
      text
        .slice(1)
        .trim();
  }
  if (!text) {
    return {
      name: '',
      args: [],
      prefixed: false
    };
  }
  const parts =
    text.split(/\s+/);
  const name =
    String(
      parts.shift() || ''
    )
      .trim()
      .toLowerCase();
  return {
    name,
    args: parts,
    prefixed
  };
}
async function execute(
  input,
  context = {}
) {
  if (
    input === undefined ||
    input === null
  ) {
    return null;
  }
  const {
    name,
    args,
    prefixed
  } = normalizeInput(input);
  if (!name) {
    return null;
  }
  if (
    commands.size === 0
  ) {
    loadCommands();
  }
  const command =
    commands.get(name);
  /*
   * CRITICAL LOOP PROTECTION
   *
   * whatsapp-web.js fires message_create
   * for messages sent by the linked account.
   *
   * That includes replies generated by
   * this bot.
   *
   * Therefore ordinary outgoing text such as:
   *
   * ❌ Unknown command
   *
   * must NEVER become another command.
   */
  if (!command) {
    /*
     * Unknown text without "." is ignored.
     *
     * This prevents the bot's own replies
     * from creating an infinite loop.
     */
    if (!prefixed) {
      return null;
    }
    return (
      `❌ Unknown command: ${name}\n` +
      `Use .menu to see available commands.`
    );
  }
  try {
    return await command.execute(
      args,
      context
    );
  } catch (error) {
    console.error(
      `[Commands] ${name} failed:`,
      error
    );
    return (
      `❌ Command failed: ${
        error.message ||
        'Unknown error'
      }`
    );
  }
}
loadCommands();
module.exports = {
  execute,
  getCommandList,
  loadCommands
};
